version: '2'
services:
# Partially copied from rhino.yml as suggested

################################################################################
#
# the CAN Interfaces for Rhino need an odsupercomponent.
#
################################################################################

    # odsupercomponent:
    #     container_name: odsupercomponent
    #     image: seresearch/opendlv-rhino-on-opendlv-on-opendlv-core-on-opendavinci-on-base:v0.1.5
    #     restart: on-failure
    #     network_mode: "host"
    #     volumes:
    #     - .:/opt/opendlv.data
    #     cap_add:
    #     - SYS_NICE
    #     entrypoint: ""
    #     command: "nice -n 0 /opt/od4/bin/odsupercomponent --configuration=/opt/opendlv.data/configuration --cid=101"

######################################################################################
#
# Microservices for RHINO (Volvo FH16).
#
######################################################################################

    dev-gps-ncom:
        container_name: dev-gps-ncom
        image: chalmersrevere/opendlv-device-gps-ncom-multi:v0.0.16
        cpuset: "1"
        restart: always
        network_mode: "host"
        cap_add:
        - SYS_NICE
        entrypoint: ""
        command: "nice -n -5 /usr/bin/opendlv-device-gps-ncom --ncom_ip=0.0.0.0 --ncom_port=3000 --cid=101 --id=0"

    opendlv-cangw-rhino:
        container_name: opendlv-cangw-rhino
        image: chalmersrevere/opendlv-device-cangw-rhino-amd64:v0.0.5
        cpuset: "1"
        restart: always
        network_mode: "host"
        privileged: true
        cap_add:
        - SYS_NICE
        entrypoint: ""
        command: "nice -n -8 /usr/bin/opendlv-device-cangw-rhino --can=can0 --cid=101 --id=1"

    vehicle-view:
        container_name: opendlv-vehicle-view
        image: chalmersrevere/opendlv-vehicle-view-multi:v0.0.60
        cpuset: "0"
        restart: always
        network_mode: "host"
        volumes:
        - ~/recordings:/opt/vehicle-view/recordings
        - /var/run/docker.sock:/var/run/docker.sock
        environment:
        - OD4SESSION_CID=101
        - PLAYBACK_OD4SESSION_CID=200
        - OPENDLV_VEHICLE_VIEW_PLATFORM=Rhino        
        ports:
        - "8081:8081"
        cap_add:
        - SYS_NICE
        entrypoint: ""
        command: "nice -n -15 node index.js"

######################################################################################
#
# Microservices from Yushu and Yue
#
######################################################################################

    can_interface:
        image: adam2092/rhino-sim-test:v0.0.10
        network_mode: "host"
        depends_on:
        - opendlv-cangw-rhino
        volumes:
        - /tmp:/tmp/
        command: "can_interface --cid=101 --freq=150 --gps-id=0 --can-id=1 "

    nominal_dynamics:
        image: adam2092/rhino-sim-test:v0.0.10
        network_mode: "host"
        volumes:
        - /tmp:/tmp
        command: "opendlv-sim-can-rhino-2 --cid=113 --cid2=101 --nominal --freq=150 --save_file=/tmp/data_nominal_states.txt  "

    virtual_control:
        image: adam2092/rhino-sim-test:v0.0.10
        depends_on:
        - nominal_dynamics
        network_mode: "host"
        volumes:
        - /tmp:/tmp
        command: "virtual_control --cid=113 --freq=150 --v_ref=13  --no_obs=3 --pos_ycenter_ob=-1.2 " 

    actual_control:
        image: adam2092/rhino-sim-test:v0.0.10
        depends_on:
        - nominal_dynamics
        network_mode: "host"
        volumes:
        - /tmp:/tmp/
        command: "actual_control --cid=113 --cid2=101 --freq=150 --k_scale_steer=1 --k_scale_acc=1" 
